config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'protos#index'
  resources :protos do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto_loury.rb
class AutoLoury < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'あり' },
    { id: 3, name: 'なし' },
  ]
end

app/models/cold_bath.rb
class ColdBath < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '20℃以上' },
    { id: 3, name: '19℃' },
    { id: 4, name: '18℃' },
    { id: 5, name: '17℃' },
    { id: 6, name: '16℃' },
    { id: 7, name: '15℃' },
    { id: 8, name: '14℃' },
    { id: 9, name: '13℃' },
    { id: 10, name: '12℃' },
    { id: 11, name: '11℃' },
    { id: 12, name: '10℃' },
    { id: 13, name: '9℃' },
    { id: 14, name: '8℃' },
    { id: 15, name: '7℃' },
    { id: 16, name: '6℃' },
    { id: 17, name: '5℃' },
    { id: 18, name: '4℃' },
    { id: 19, name: '3℃' },
    { id: 20, name: '2℃' },
    { id: 21, name: '1℃' },
    { id: 22, name: '0℃以下' },
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :proto
  belongs_to :user
end

app/models/invigorate.rb
class Invigorate < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'あり' },
    { id: 3, name: 'なし' },
  ]
end

app/models/loury.rb
class Loury < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'あり' },
    { id: 3, name: 'なし' },
  ]
end

app/models/outside.rb
class Outside < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'あり' },
    { id: 3, name: 'なし' },
  ]
end

app/models/proto.rb
class Proto < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :sauna
  belongs_to :cold_bath
  belongs_to :loury
  belongs_to :auto_loury
  belongs_to :self_loury
  belongs_to :outside
  belongs_to :invigorate
  belongs_to :water

  belongs_to :user
  has_one_attached :image
  has_many :comments
end

app/models/sauna.rb
class Sauna < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '140℃以上' },
    { id: 3, name: '135℃' },
    { id: 4, name: '130℃' },
    { id: 5, name: '125℃' },
    { id: 6, name: '120℃' },
    { id: 7, name: '115℃' },
    { id: 8, name: '110℃' },
    { id: 9, name: '105℃' },
    { id: 10, name: '100℃' },
    { id: 11, name: '95℃' },
    { id: 12, name: '90℃' },
    { id: 13, name: '85℃' },
    { id: 14, name: '80℃' },
    { id: 15, name: '75℃' },
    { id: 16, name: '70℃' },
    { id: 17, name: '65℃' },
    { id: 18, name: '60℃以下' },
  ]
end

app/models/self_loury.rb
class SelfLoury < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'あり' },
    { id: 3, name: 'なし' },
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
  validates :nickname
  validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
  validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
  validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }
  end

  has_many :protos
  has_many :comments
end

app/models/water.rb
class Water < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'あり' },
    { id: 3, name: 'なし' },
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :nickname, :first_name, :last_name, :first_name_kana, :last_name_kana])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/protos/#{comment.proto.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, proto_id: params[:proto_id])
  end
end

app/controllers/protos_controller.rb
class ProtosController < ApplicationController
  def index 
    @protos = Proto.all.order(created_at: :desc)
  end

  def new
    @proto = Proto.new
  end

  def create
    @proto = Proto.create(proto_params)
    if @proto.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @proto = Proto.find(params[:id])
  end

  def edit
    @proto = Proto.find(params[:id])
  end

  def update
    @proto = Proto.find(params[:id])
    @proto.update(proto_params)
    if @proto.update(proto_params)
      redirect_to proto_path
    else
      render :edit
    end
  end

  def destroy
    @proto = Proto.find(params[:id])
    if @proto.user_id == current_user.id
      @proto.destroy
    end
    redirect_to root_path
  end
  
  private

  def proto_params
    params.require(:proto).permit(:image, :title, :post_text, :sauna_id, :cold_bath_id, :loury_id, :auto_loury_id, :self_loury_id, :outside_id, :invigorate_id, :water_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/protos_helper.rb
module ProtosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaunaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/protos/edit.html.erb
<%= render "shared/second-header"%>

<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">投稿内容を入力</h2>
    <%= form_with(model: @proto, local: true) do |f| %>

    <%# <%= render 'shared/error_messages', model: f.object %> 
    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        title
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"title", placeholder:"title（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          投稿の説明
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.text_area :post_text, class:"items-text", id:"post-info", placeholder:"投稿の説明（必須 1,000文字まで）例）サウナしきじに行ってきました。こちらのサウナは水風呂の水が富士山の天然水なのでそのまま飲むことができます。また椅子は全部で９つあり、ベンチが２つあります。",rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">投稿の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          サウナの室温
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:sauna_id, Sauna.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          水風呂の水温
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:cold_bath_id, ColdBath.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          ロウリュ
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:loury_id, Loury.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          オートロウリュ
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:auto_loury_id, AutoLoury.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          セルフロウリュ
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:self_loury_id, SelfLoury.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          外気浴
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:outside_id, Outside.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          整いスペース
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:invigorate_id, Invigorate.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          給水機
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:water_id, Water.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', proto_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/protos/index.html.erb
<%= render "shared/header" %>

<%# メイン画面 %>
<div class="hero vh-100 d-flex align-items-center">
  <section class="container">
    <div class="row">
      <div class="col-lg-7 mx-auto text-center">
        <h1 class="display-4 text-white">Sauna Zen</h1>
        <p class="text-white my-3">Sauna is an excellent way to relax and rejuvenate your body. It helps relieve stress, improves circulation, cleanses the skin, and promotes muscle relaxation.</p>
        <p>
          <%# <a href="#" class="btn btn-primary my-2">サ活投稿</a> %>
          <%= link_to 'サ活投稿', new_proto_path, class: "btn btn-primary me-2" %>
          <%# <a href="#" class="btn btn-warning my-2">サ飯投稿</a> %>
          <%= link_to 'サ飯投稿', '#', class: "btn btn-warning" %>
        </p>
      </div>
    </div>
  </section>
</div>
<%# メイン画面 %>

<%# /投稿一覧 %>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @protos.each do |proto| %>
      <div class="col">
        <div class="card shadow-sm d-flex align-items-center">
            <div class='item-img-content'>
              <%= image_tag proto.image, class: "item-img" %>
            </div>
          <div class="card-body">
            <h3 class='card-text'>
              <%= proto.title %>  
            </h3>
            <p class="card-text">
              <span>サウナ室<%= proto.sauna.name %><br>水風呂<%= proto.cold_bath.name %></span> 
            </p>
            <%= link_to proto_path(proto.id) do %>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %> 
    </div>
    <% if @protos.blank? then %>
      <li class='list'>
        <%= link_to '#' do %> 
        <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %> 
        <div class='item-info'>
          <h3 class='item-name'>
            サ活を投稿しよう！
          </h3>
          <div class='item-price'>
            <span>サウナ室<br>水風呂</span>
          </div>
        </div>
        <% end %> 
      </li>
    <% end %> 
  </div>
</div>

<%= render "shared/footer" %>

app/views/protos/new.html.erb
<%= render "shared/second-header"%>

<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">投稿内容を入力</h2>
    <%= form_with(model: @proto, local: true) do |f| %>

    <%# <%= render 'shared/error_messages', model: f.object %> 
    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        title
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"title", placeholder:"title（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          投稿の説明
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.text_area :post_text, class:"items-text", id:"post-info", placeholder:"投稿の説明（必須 1,000文字まで）例）サウナしきじに行ってきました。こちらのサウナは水風呂の水が富士山の天然水なのでそのまま飲むことができます。また椅子は全部で９つあり、ベンチが２つあります。",rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">投稿の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          サウナの室温
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:sauna_id, Sauna.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          水風呂の水温
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:cold_bath_id, ColdBath.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          ロウリュ
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:loury_id, Loury.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          オートロウリュ
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:auto_loury_id, AutoLoury.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          セルフロウリュ
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:self_loury_id, SelfLoury.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          外気浴
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:outside_id, Outside.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          整いスペース
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:invigorate_id, Invigorate.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          給水機
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:water_id, Water.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/protos/show.html.erb
<%= render "shared/second-header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @proto.user.nickname %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @proto.image,class:"item-box-img" %>
    </div>
    <% if user_signed_in? %>
      <% if current_user.id == @proto.user.id %>
        <%= link_to "編集", edit_proto_path, method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", proto_path, method: :delete, class:"item-destroy" %>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @proto.title %></span>
    </div>
    <div class="item-explain-box">
      <span><%= @proto.post_text %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">サウナの室温</th>
          <td class="detail-value"><%= @proto.sauna.name %></td>
        </tr>
        <tr>
          <th class="detail-item">水風呂の水温</th>
          <td class="detail-value"><%= @proto.cold_bath.name %></td>
        </tr>
        <tr>
          <th class="detail-item">ロウリュ</th>
          <td class="detail-value"><%= @proto.loury.name %></td>
        </tr>
        <tr>
          <th class="detail-item">オートロウリュ</th>
          <td class="detail-value"><%= @proto.auto_loury.name %></td>
        </tr>
        <tr>
          <th class="detail-item">セルフロウリュ</th>
          <td class="detail-value"><%= @proto.self_loury.name %></td>
        </tr>
        <tr>
          <th class="detail-item">外気浴</th>
          <td class="detail-value"><%= @proto.outside.name %></td>
        </tr>
        <tr>
          <th class="detail-item">整いスペース</th>
          <td class="detail-value"><%= @proto.invigorate.name %></td>
        </tr>
        <tr>
          <th class="detail-item">給水機</th>
          <td class="detail-value"><%= @proto.water.name %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%# <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%> 
        <span>コメントする<span>
      </button>
    </form>
  </div>
</div>

<%= render "shared/second-footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-muted py-5 bg-primary">
  <div class="container d-flex flex-wrap align-items-center justify-content-center justify-content-lg-end">
    <p class="float-end mb-1 ">
      <a href="#" button type="button" class="btn btn-outline-light me-2 ">Back to top</a>
    </p>
    <!-- <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="../getting-started/introduction/">getting started guide</a>.</p> -->
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="p-3 bg-primary text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <!-- <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"> -->
      <nav class="navbar navbar-expand-lg navbar-light nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <div class="container-fluid">
          <a class="navbar-brand text-white" href="/">Sauna Zen</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </nav>
      <!-- </ul> -->

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
      </form>

      <% if user_signed_in? %>
        <div class="text-end">
          <%# <a href="/users/sign_out" class="btn btn-outline-light me-2">Logout</a> %>
          <%= link_to 'Log-out', destroy_user_session_path, method: :delete, class: "btn btn-outline-light me-2" %>
          <%# <a href="#" class="btn btn-outline-light me-2"></a> %>
          <%= link_to current_user.nickname, "#", class: "btn btn-outline-light me-2" %>
        </div>
      <% else %>
        <div class="text-end">
          <%# <a href="/users/sign_in" class="btn btn-outline-light me-2">Log-in</a> %>
          <%= link_to 'Log-in', new_user_session_path, class: "btn btn-outline-light me-2" %>
          <%# <a href="/users/sign_up" class="btn btn-outline-light me-2">Sign-up</a> %>
          <%= link_to 'sign-up', new_user_registration_path, class: "btn btn-outline-light me-2" %>
        </div>
      <% end %>

    </div>
  </div>
</header>

app/views/shared/_second-footer.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%# <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%> 
</footer>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%# <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%> 
</footer>

app/views/shared/_second-header.html.erb
<header class="p-3 bg-primary text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <!-- <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"> -->
      <nav class="navbar navbar-expand-lg navbar-light nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <div class="container-fluid">
          <a class="navbar-brand text-white " href="/">Sauna Zen</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </nav>
      <!-- </ul> -->

      <%# <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
      </form> %>

    </div>
  </div>
</header>